spring:
  profiles:
    active: dev
  application:
    name: edu-backend

server:
  port: 8080

jwt:
  secret: edu-backend-secret-key-edu-backend-secret-key-edu-backend-secret-key
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
