spring:
  profiles:
    active: dev
  application:
    name: edu-backend

server:
  port: 8080

jwt:
  secret: edu-backend-secret-key-edu-backend-secret-key-edu-backend-secret-key
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

    # 自定义 deepseek 配置
deepseek:
  api:
    key:
    url: https://api.deepseek.com/v1/chat/completions
    model: deepseek-chat
